const prices={8:{inr:199,usd:4.99},12:{inr:299,usd:6.99},16:{inr:399,usd:8.99},20:{inr:499,usd:10.99},24:{inr:599,usd:12.99},32:{inr:799,usd:16.99}};
const types=['Baby / Child','Couple','Family','Best Friend','Someone Special'];
const occasions=['Birthday','Baby Shower','New Baby','First Birthday','Anniversary','Wedding','Engagement','Proposal / Love','Graduation','Durga Puja','Bhai Phonta','Diwali','Eid','Christmas','Holi','Saraswati Puja','Ganesh Chaturthi','Janmashtami','Pohela Boishakh','Dussehra','Navratri','Raksha Bandhan','Annaprashan','Family','Best Friend','Custom / Other'];
const steps=['Who is this magical storybook for?','Choose the magic you want to celebrate','Choose Your TinyTales Book','Tell Us Their Story','Bring Your Memories Into The Story','Your Magical Book Is Ready'];
const kickers=['CREATE TINyTALES','OCCASION','BOOK CONFIGURATION','PERSONALIZATION','MEMORIES','PREVIEW • APPROVAL'];
const refs=['01-forest-portal.png','02-landing-page.jpg','03-forest-home.jpg','04-menu-cards.jpg','05-homepage.jpg','06-who-is-it-for.jpg','07-occasions.jpg','08-book-config.jpg','09-story-personalization.jpg','10-photo-upload.jpg','11-character-preview.jpg','12-theme-font.jpg','13-full-book-preview.jpg','14-checkout.jpg','15-old-landing-page.png','16-old-forest.png','17-old-menu.png','18-old-homepage.png','19-old-portal.png'];
const state={step:1,type:'Baby / Child',occasion:'Birthday',product:'Personalized Storybook',language:'English',pages:8,title:'',name:'',relationship:'',details:'',memories:'',storySource:'TinyTales Original Story',ownStory:'',photos:[],approved:false,paid:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'\\\\','"':'&quot;'}[m]))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2200)}
function save(){try{sessionStorage.setItem('tinytalesFinalDraft',JSON.stringify(state))}catch(e){}}
function load(){try{const x=JSON.parse(sessionStorage.getItem('tinytalesFinalDraft')||'null');if(x)Object.assign(state,x)}catch(e){}}
function choices(items,key){return `<div class="option-grid">${items.map(v=>`<button class="choice ${state[key]===v?'active':''}" data-key="${key}" data-value="${esc(v)}">${v}</button>`).join('')}</div>`}
function renderPrices(){ $('#priceGrid').innerHTML=[8,16,32].map(p=>`<article class="price-card ${p===16?'featured':''}"><b>${p} Pages</b><strong>₹${prices[p].inr}</strong><small>$${prices[p].usd} international</small></article>`).join('') }
function renderStep(){
 $('#stepKicker').textContent=kickers[state.step-1];$('#stepTitle').textContent=steps[state.step-1];$('#progress').style.width=`${state.step/6*100}%`;$('#dots').innerHTML=Array.from({length:6},(_,i)=>`<span class="${i<state.step?'active':''}"></span>`).join('');
 let h='';
 if(state.step===1) h=choices(types,'type');
 if(state.step===2) h=choices(occasions,'occasion');
 if(state.step===3) h=`<div class="field"><label>Product / Story Type</label>${choices(['Personalized Storybook','Gift Card'],'product')}</div><div class="field" style="margin-top:16px"><label>Language</label>${choices(['English','বাংলা','हिन्दी'],'language')}</div><div class="field" style="margin-top:16px"><label>Book Length</label>${choices([8,12,16,20,24,32],'pages')}</div>`;
 if(state.step===4) h=`<div class="field-grid"><div class="field full"><label>Story Title</label><input id="title" value="${esc(state.title)}" placeholder="Give your story a magical title"></div><div class="field"><label>Name</label><input id="name" value="${esc(state.name)}" placeholder="Name"></div><div class="field"><label>Relationship</label><input id="relationship" value="${esc(state.relationship)}" placeholder="Relationship"></div><div class="field"><label>Personal Details</label><textarea id="details" placeholder="Important details">${esc(state.details)}</textarea></div><div class="field"><label>Special Memories</label><textarea id="memories" placeholder="A memory you want included">${esc(state.memories)}</textarea></div><div class="field full"><label>Story Source</label>${choices(['TinyTales Original Story','Your Own Story'],'storySource')}</div>${state.storySource==='Your Own Story'?`<div class="field full"><label>Your Own Story</label><textarea id="ownStory" placeholder="Write or paste your story">${esc(state.ownStory)}</textarea></div>`:''}</div>`;
 if(state.step===5) h=`<div class="upload"><div class="icon">📷</div><h3>Bring Your Memories Into The Story</h3><p>Default mix: 50% real photos + 50% AI storybook illustrations. One main image per story page; no collage.</p><label class="primary" style="display:inline-block">Add Photos<input id="photos" type="file" accept="image/*" multiple hidden></label><div class="photo-list">${state.photos.map(n=>`<span class="photo-chip">${esc(n)}</span>`).join('')}</div><p style="font:12px Arial;color:#aaa">Original uploaded photos are intended for temporary processing and deletion, not permanent backup storage.</p></div>`;
 if(state.step===6) h=`<div class="approval"><div class="preview-spread"><div class="preview-page"><div class="watermark">PREVIEW — TINyTALES</div><h3>${esc(state.title||'Your Magical Story')}</h3><p>${esc(state.name||'Your loved one')} • ${state.occasion}</p><p>This is the full-book review stage. Edit or regenerate before approval.</p></div><div class="preview-page"><h3>Storybook Page</h3><p>Real memories + story-driven AI illustration pages.</p></div></div><div class="review-box"><h3>Premium Review</h3><button class="choice" id="editBtn">Edit</button><button class="choice" id="regenBtn">Regenerate Page</button><button class="choice ${state.approved?'active':''}" id="approveBtn">Looks Perfect</button><p style="font:13px Arial;color:#bbb">HD Quality Download Available After Payment</p><div class="payment-box"><b>${state.pages} story pages</b><div>India ₹${prices[state.pages].inr} / International $${prices[state.pages].usd}</div></div></div></div>`;
 $('#stepBody').innerHTML=h;bindStep();updateLive();$('#backBtn').style.visibility=state.step===1?'hidden':'visible';$('#nextBtn').textContent=state.step===6?'Continue to Payment':'Continue';
}
function bindStep(){
 $$('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key;state[k]=k==='pages'?Number(b.dataset.value):b.dataset.value;save();renderStep()});
 const map={title:'title',name:'name',relationship:'relationship',details:'details',memories:'memories',ownStory:'ownStory'};Object.keys(map).forEach(id=>{const e=$('#'+id);if(e)e.oninput=()=>{state[map[id]]=e.value;save();updateLive()}});
 const f=$('#photos');if(f)f.onchange=e=>{state.photos.push(...[...e.target.files].map(x=>x.name));save();renderStep();toast(`${e.target.files.length} photo(s) added`)};
 if($('#editBtn'))$('#editBtn').onclick=()=>{state.step=4;state.approved=false;renderStep();toast('Edit mode opened')};
 if($('#regenBtn'))$('#regenBtn').onclick=()=>toast('Only the failed/selected page would be regenerated by the AI backend');
 if($('#approveBtn'))$('#approveBtn').onclick=()=>{state.approved=true;save();renderStep();toast('Preview approved. Payment is next.')};
}
function updateLive(){$('#liveType').textContent=state.type;$('#liveOccasion').textContent=state.occasion;$('#liveLang').textContent=state.language;$('#livePages').textContent=`${state.pages} Pages`;$('#liveTitle').textContent=state.title||'Your Magical Story';$('#liveMeta').textContent=`${state.type} • ${state.occasion}`}
function openWizard(){load();state.step=1;renderStep();$('#wizard').showModal()}
$('#nextBtn').onclick=()=>{if(state.step<6){state.step++;save();renderStep()}else if(!state.approved){toast('Please click “Looks Perfect” before payment')}else openPayment()};$('#backBtn').onclick=()=>{if(state.step>1){state.step--;renderStep()}};
function openPayment(){const id='TT-'+new Date().getFullYear()+'-'+Math.random().toString(36).slice(2,8).toUpperCase();const d=document.createElement('dialog');d.className='small-dialog';d.innerHTML=`<h2>Order & Payment</h2><p><b>Order ID:</b> ${id}</p><p>${state.type} • ${state.occasion} • ${state.language} • ${state.pages} pages</p><div class="payment-box"><h3>Final Price</h3><b>India: ₹${prices[state.pages].inr}</b><br><b>International: $${prices[state.pages].usd}</b><p style="font:12px Arial;color:#aaa">India → UPI / Razorpay<br>International → PayPal</p></div><p style="font:12px Arial;color:#aaa">Demo mode: no real payment is charged. Production gateways and secrets must remain server-side.</p><button class="primary" id="payNow">Pay Now (Demo)</button> <button class="secondary" id="cancelPay">Cancel</button>`;document.body.appendChild(d);d.showModal();$('#cancelPay').onclick=()=>d.close();$('#payNow').onclick=()=>{state.paid=true;save();d.close();toast('Demo payment verified. HD download stage unlocked.');setTimeout(()=>showFinal(id),350)}}
function showFinal(id){const d=document.createElement('dialog');d.className='small-dialog';d.innerHTML=`<h2>Payment Successful ✦</h2><p><b>Order:</b> ${id}</p><p>Payment Verified → Paid → Book Generation → QC → Final HD Download</p><p style="font:13px Arial;color:#c8c0ca">Your approved version is protected. In production, the real HD PDF download is released only after verified payment.</p><button class="primary" id="downloadDemo">Download HD PDF (Demo)</button><button class="secondary" id="reviewDemo">Give 1–5 Star Review</button>`;document.body.appendChild(d);d.showModal();$('#downloadDemo').onclick=()=>toast('Demo only — connect the PDF generator/storage endpoint for the real HD file');$('#reviewDemo').onclick=()=>{toast('Review stage recorded in demo');d.close()}}
$('[data-start]').onclick=openWizard;$$('[data-start]').forEach(b=>b.onclick=openWizard);$$('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
$$('.occasion-mini button').forEach(b=>b.onclick=()=>{state.type=b.dataset.type;openWizard()});
$('#loginBtn').onclick=()=>$('#login').showModal();$('#supportBtn').onclick=()=>$('#support').showModal();$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
$('#refsBtn').onclick=()=>{$('#refsGrid').innerHTML=refs.map((r,i)=>`<figure><img src="assets/reference-screens/${r}" loading="lazy" alt="TinyTales design reference ${i+1}"><figcaption>${r}</figcaption></figure>`).join('');$('#refs').showModal()};
renderPrices();load();updateLive();
 
